language: generic

git:
  autocrlf: "true; echo test"

matrix:
  include:
   - name: amd64 bionic
     os: linux
     dist: bionic
     arch: amd64
   - os: arm64 xenial
     dist: xenial
     arch: arm64
   - os: arm64 bionic
     dist: bionic
     arch: arm64
   - os: ppc64le
     dist: xenial
     arch: ppc64le
   - os: s390x
     arch: s390x


script: echo $TRAVIS_CPU_ARCH

