language: generic

matrix:
  include:
   - name: Some reeeeeeeeeeaaaaaaaally reeeeeeeeeeaaaaaaaally reeeeeeeeeeaaaaaaaally long name goes here
     os: linux
     env: DIST=precise
     dist: precise
     arch: arm64
   - name: Random stage name
     os: linux
     env: DIST=trusty
     dist: trusty
     arch: arm64
   - name: Default arch
     os: linux
     env: DIST=bionic
     dist: bionic
   - name: AMD arch
     os: linux
     env: DIST=bionic
     dist: bionic
     arch: amd64
   - os: linux
     env: DIST=xenial
     dist: xenial
     arch: arm64
   - os: linux
     env: DIST=bionic
     dist: bionic
     arch: arm64


script: echo hi
