language: generic

os: linux

jobs:
  include:
   - name: amd64 bionic
     dist: bionic
     arch: amd64
   - name: arm64 xenial
     dist: xenial
     arch: arm64
   - name: arm64 bionic
     dist: bionic
     arch: arm64
   - name: ppc64le
     dist: xenial
     arch: ppc64le
   - name: s390x
     arch: s390x


script: echo $TRAVIS_CPU_ARCH

